### PR TITLE
Refactor GUI to allow refreshing components via callbacks.

### PR DESCRIPTION
**Pull request by kevinzakka**

### CODE REVIEW

**Comment by kevinzakka** [comment]
Hi @zalo, did a refactor which I hope isn't too cumbersome. It adds the following:

- A help menu, toggled via F1.
- A `updateGUICallbacks`, which is a list of callbacks that get executed after a scene is reloaded.

Probably did some unconventional javascript things, so feel free to edit!

**Comment by kevinzakka** [comment]
- Gray out keyframes if there are none in the model.
- Reset the camera on scene reload / model change.
- More help menu additions.

**Comment by kevinzakka** [comment]
Added object highlighting, but seems buggy on my piano environment.

**Comment by zalo** [comment]
What's the purpose of the highlighting?   I always found the highlighting based aspects of the original MuJoCo viewer to be kind of cumbersome...

**Comment by kevinzakka** [comment]
Highlighting is great once you can display labels like body names or geom names and filter to only display those for the select body / geom. I've used it a lot when fixing XML files or porting a URDF to XML.

**Comment by kevinzakka** [comment]
@zalo Don't mind removing it for this PR and separating it out into another. LMK!

**Comment by zalo** [comment]
Ah, no, it's fine; I was mostly just thinking about the way the dragging needs highlighting and then the use of the Ctrl+ or Shift+ Drag to move things around..  Probably my least favorite part of the standard MuJoCo visualizers.

If it's just for displaying visual data, we can probably do it on hover and save the users' a double click...

**Comment by yuvaltassa** [comment]
@zalo, we are very much aware of the shortcomings of the current visualiser conventions, see e.g. [this proposal](https://github.com/deepmind/mujoco/discussions/297), but coming up with a replacement that would be both as powerful in terms of available actions and more intuitive seems quite difficult. Looking ahead, not just at touchpads (which are becoming more common than mice), but at pure touch interfaces like tablets and phones, this question seems more urgent yet even more difficult. We would love to hear your thoughts on this, with the common goals of finding consensus for all-around improvements and preventing divergence of UI conventions. 

Cheers 🙂

**Comment by zalo** [comment]
Thanks @yuvaltassa , I wrote up how I'm currently doing it in the example in your issue.   If there are major drawbacks to it, then there might need to be a mode toggle between the "Newbie/Mobile-friendly Controls" and the "Original Controls".

(Just an FYI @kevinzakka : I believe calling `const mujoco = await load_mujoco();` in the utilities file creates a second mujoco WebAssembly instance which isn't ideal... I'd like to figure out a solution for getting intellisense working in secondary modules at some point, but it's best not to commit it if using it just for intellisense for now...)

P.S. Thank you for your continued support and development of MuJoCo!

**Comment by kevinzakka** [comment]
@zalo Noted, I was using it for intellisense while coding. Will take it out for final commit!

**Comment by zalo** [comment]
I'm probably going to do an invasive thing where all this new UI stuff gets moved to another separate utility file before merging; I'm trying to keep the main example file somewhat short and concise (by three.js standards) so it's easy to grasp how the plugin fits together (for three.js veterans, but MuJoCo newcomers).

**Comment by kevinzakka** [comment]
That sounds like a good plan, agreed!

**Pull request merged**
