### PR TITLE
Add pause button.

### PR DESCRIPTION
**Pull request by kevinzakka**

### CODE REVIEW

**Comment by kevinzakka** [comment]
WIP, I am also adding control noise.

**Comment by kevinzakka** [comment]
Actuator sliders not changing when scene is changed (e.g. humanoid to hand). Need to debug.

**Comment by kevinzakka** [comment]
Nice! I was struggling to get the sliders to reset (was working on it just now) haha

**Comment by zalo** [comment]
Yeah, sorry for clobbering your changes; I'll get this merged in and let you work in your own branch 🙃

**Pull request merged**
